# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69955dc23776be8dd9c1d42c32985094f73c765e9549856e24a81451305668d02d2955a5a98c977d64b492e75f3ccfce954af67741503edbc86c20d9e6d4b930

test:
  secret_key_base: 7928c970601207f21335fd9e9283c3382bdb7dffa8523e1c238252a32ca20ca71dc6e7c2f8d8eecdfd850a887d916e5b0521575f2075da61dc271834f7f24506

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
